# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # give access to runner/server
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #NB
      - uses: actions/checkout@v3
      # this workflow has more than one job
      #name species a new job

      # Runs a set of commands using the runners shell
      - name: Set up global variables
        run: |
          git config --global user.name "Germina"
          git config --global user.email "germinangwepe3@gmail.com"

      - name: Append current date and name
        run: |
          echo "Germina" >> File1.txt

      - name: Commit code
        run: |
          git add .
          git commit -m "Append current date and name to file"
          git push origin main
